name: ncnn_yolox_flutter_example
description: Demonstrates how to use the ncnn_yolox_flutter plugin.

publish_to: "none"

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  adaptive_dialog: ^1.8.0+1
  camera: ^0.10.0+4
  flutter:
    sdk: flutter
  flutter_image_compress: ^1.1.3
  freezed_annotation: ^2.2.0
  hooks_riverpod: ^2.1.1
  image: ^4.0.17
  image_picker: ^0.8.6
  ncnn_yolox_flutter:
    path: ../
  path_provider: ^2.0.11

dev_dependencies:
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  pedantic_mono: ^1.20.1

flutter:
  uses-material-design: true
  assets:
    - assets/yolox/
