name: ncnn_yolox_flutter_example
description: Demonstrates how to use the ncnn_yolox_flutter plugin.

publish_to: "none"

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  camera: ^0.10.0+4
  flutter:
    sdk: flutter
  hooks_riverpod: ^2.0.2
  image: ^3.2.2
  image_picker: ^0.8.6
  ncnn_yolox_flutter:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic_mono: any

flutter:
  uses-material-design: true
  assets:
    - assets/yolox/
