version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: "pub"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10

  - package-ecosystem: "pub example"
    directory: "example"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
