name: ncnn_yolox_flutter
description: This is a plugin to run YOLOX on ncnn.
version: 0.3.0
homepage: https://github.com/KoheiKanagu/ncnn_yolox_flutter

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  ffi: ">=1.1.2 <3.0.0"
  flutter:
    sdk: flutter
  freezed_annotation: ^2.0.3
  path_provider: ^2.0.9

dev_dependencies:
  build_runner: ^2.1.11
  flutter_test:
    sdk: flutter
  freezed: ^2.0.3+1
  pedantic_mono: any

flutter:
  plugin:
    platforms:
      android:
        package: dev.kingu.ncnn_yolox_flutter
        pluginClass: NcnnYoloxFlutterPlugin
      ios:
        pluginClass: NcnnYoloxFlutterPlugin
